//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventarioGerenciamento.Web.Models.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class categorias
    {
        public byte cat_Id { get; set; }
        public string cat_Nome { get; set; }
        public byte cat_Status { get; set; }
    }
}
