//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventarioGerenciamento.Web.Models.DAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class funcao
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public funcao()
        {
            this.usuario = new HashSet<usuario>();
        }
    
        [Key]
        public byte f_Id { get; set; }

        [Display(Name = "Nome da Funçao")]
        [Required(ErrorMessage = "*")]
        public string f_Nome { get; set; }

        [Display(Name = "Status da Funçao")]
        [Required(ErrorMessage = "*")]
        public byte f_Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<usuario> usuario { get; set; }
    }
}
